INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('IN','CNTRY','A','India','India',1,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);
INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('PAK','CNTRY','A','Pakistan','Pakistan',2,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);
INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('US','CNTRY','A','United States','United States',3,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);
INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('GER','CNTRY','A','Germany','Germany',4,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);
INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('FR','CNTRY','A','France','France',5,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);
INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('NZ','CNTRY','A','New Zealand','New Zealand',6,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);
INSERT INTO PROJ.REFERENCE_DATA_ELEMENT (ELEMENT_CODE, CATEGORY_CODE, ACTIVE_FLAG, ELEMENT_DESC, ELEMENT_VALUE,
ORDER_SEQ, ACTIVE_TIMESTAMP, EXPIRY_TIMESTAMP, UPDATE_USER_ID, UPDATE_TIMESTAMP, LOCALE, CHANNEL_ID, CREATED_USER_ID,
CREATED_TIMESTAMP) VALUES ('RSA','CNTRY','A','Russia','Russia',7,CURRENT_TIMESTAMP,NULL,'SACHIN',CURRENT_TIMESTAMP,
'en_US','INTA','SACHIN',CURRENT_TIMESTAMP);